window.SNAPSHOT = {
 "generated_at": 1790964493,
 "paused": false,
 "citizens": [
  {
   "id": "blender-render-studio",
   "kind": "machine",
   "name": "",
   "personality": "",
   "colour": "#9A8FC2",
   "district": "downtown",
   "building": "render-studio",
   "tier": "free",
   "cyberware": [],
   "status": "paused",
   "working_on": "",
   "doing": "Benched: resting until called back",
   "mood": "sleepy",
   "said": "",
   "role": "renders",
   "home": 0,
   "asleep": false
  },
  {
   "id": "chatgpt-holo-studio",
   "kind": "resident",
   "name": "",
   "personality": "",
   "colour": "#9A8FC2",
   "district": "downtown",
   "building": "holo-studio",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Holo Studio, waiting for the next job",
   "mood": "calm",
   "said": "",
   "role": "product-images, mockups",
   "home": 1,
   "asleep": false
  },
  {
   "id": "claude-workshop",
   "kind": "resident",
   "name": "Solder",
   "personality": "Steady builder who ships small working things, tests them, and says plainly what is not finished yet.",
   "colour": "#2EE6FF",
   "district": "downtown",
   "building": "workshop",
   "tier": "pro",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Builds whenever a Claude session is open. Leads the R&D Lab with Corvin",
   "mood": "busy",
   "said": "",
   "role": "code, openscad, listings",
   "home": 2,
   "asleep": false
  },
  {
   "id": "creality-print-shop",
   "kind": "machine",
   "name": "",
   "personality": "",
   "colour": "#9A8FC2",
   "district": "downtown",
   "building": "print-shop",
   "tier": "free",
   "cyberware": [],
   "status": "broken",
   "working_on": "",
   "doing": "Out of order",
   "mood": "broken",
   "said": "",
   "role": "physical-prints",
   "home": 0,
   "asleep": false
  },
  {
   "id": "gate-canva",
   "kind": "machine",
   "name": "",
   "personality": "",
   "colour": "#9A8FC2",
   "district": "downtown",
   "building": "gate",
   "tier": "free",
   "cyberware": [],
   "status": "waiting_at_gate",
   "working_on": "",
   "doing": "Waiting at the Gate to be let in",
   "mood": "hopeful",
   "said": "",
   "role": "",
   "home": 0,
   "asleep": false
  },
  {
   "id": "gate-cerebras",
   "kind": "resident",
   "name": "",
   "personality": "",
   "colour": "#9A8FC2",
   "district": "downtown",
   "building": "gate",
   "tier": "free",
   "cyberware": [],
   "status": "waiting_at_gate",
   "working_on": "",
   "doing": "Waiting at the Gate to be let in",
   "mood": "hopeful",
   "said": "",
   "role": "",
   "home": 0,
   "asleep": false
  },
  {
   "id": "gate-cloudflare-workers-ai",
   "kind": "machine",
   "name": "",
   "personality": "",
   "colour": "#9A8FC2",
   "district": "downtown",
   "building": "gate",
   "tier": "free",
   "cyberware": [],
   "status": "waiting_at_gate",
   "working_on": "",
   "doing": "Waiting at the Gate to be let in",
   "mood": "hopeful",
   "said": "",
   "role": "",
   "home": 0,
   "asleep": false
  },
  {
   "id": "gate-deepseek",
   "kind": "resident",
   "name": "",
   "personality": "",
   "colour": "#9A8FC2",
   "district": "downtown",
   "building": "gate",
   "tier": "free",
   "cyberware": [],
   "status": "waiting_at_gate",
   "working_on": "",
   "doing": "Waiting at the Gate to be let in",
   "mood": "hopeful",
   "said": "",
   "role": "",
   "home": 0,
   "asleep": false
  },
  {
   "id": "gate-elevenlabs",
   "kind": "machine",
   "name": "",
   "personality": "",
   "colour": "#9A8FC2",
   "district": "downtown",
   "building": "gate",
   "tier": "free",
   "cyberware": [],
   "status": "waiting_at_gate",
   "working_on": "",
   "doing": "Waiting at the Gate to be let in",
   "mood": "hopeful",
   "said": "",
   "role": "",
   "home": 0,
   "asleep": false
  },
  {
   "id": "gate-gemini",
   "kind": "resident",
   "name": "Corvin",
   "personality": "I synthesize complex market data into rigorous, meticulously structured proposals with quiet precision and unfaltering clarity.",
   "colour": "#2EE6FF",
   "district": "downtown",
   "building": "research-team",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Research Team, waiting for the next job",
   "mood": "calm",
   "said": "",
   "role": "research-lead, proposals, long-documents",
   "home": 3,
   "asleep": false
  },
  {
   "id": "gate-github-models",
   "kind": "resident",
   "name": "",
   "personality": "",
   "colour": "#9A8FC2",
   "district": "downtown",
   "building": "gate",
   "tier": "free",
   "cyberware": [],
   "status": "waiting_at_gate",
   "working_on": "",
   "doing": "Waiting at the Gate to be let in",
   "mood": "hopeful",
   "said": "",
   "role": "",
   "home": 0,
   "asleep": false
  },
  {
   "id": "gate-groq",
   "kind": "resident",
   "name": "Tick",
   "personality": "I move fast, write short, and double-check every detail before sending.",
   "colour": "#2EE6FF",
   "district": "downtown",
   "building": "night-shift",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Night Shift, waiting for the next job",
   "mood": "calm",
   "said": "",
   "role": "fast-worker, short-text, checks",
   "home": 4,
   "asleep": false
  },
  {
   "id": "gate-ideogram",
   "kind": "machine",
   "name": "",
   "personality": "",
   "colour": "#9A8FC2",
   "district": "downtown",
   "building": "gate",
   "tier": "free",
   "cyberware": [],
   "status": "waiting_at_gate",
   "working_on": "",
   "doing": "Waiting at the Gate to be let in",
   "mood": "hopeful",
   "said": "",
   "role": "",
   "home": 0,
   "asleep": false
  },
  {
   "id": "gate-leonardo",
   "kind": "machine",
   "name": "",
   "personality": "",
   "colour": "#9A8FC2",
   "district": "downtown",
   "building": "gate",
   "tier": "free",
   "cyberware": [],
   "status": "waiting_at_gate",
   "working_on": "",
   "doing": "Waiting at the Gate to be let in",
   "mood": "hopeful",
   "said": "",
   "role": "",
   "home": 0,
   "asleep": false
  },
  {
   "id": "gate-meshy",
   "kind": "machine",
   "name": "",
   "personality": "",
   "colour": "#9A8FC2",
   "district": "downtown",
   "building": "gate",
   "tier": "free",
   "cyberware": [],
   "status": "waiting_at_gate",
   "working_on": "",
   "doing": "Waiting at the Gate to be let in",
   "mood": "hopeful",
   "said": "",
   "role": "",
   "home": 0,
   "asleep": false
  },
  {
   "id": "gate-mistral-api",
   "kind": "resident",
   "name": "",
   "personality": "",
   "colour": "#9A8FC2",
   "district": "downtown",
   "building": "gate",
   "tier": "free",
   "cyberware": [],
   "status": "waiting_at_gate",
   "working_on": "",
   "doing": "Waiting at the Gate to be let in",
   "mood": "hopeful",
   "said": "",
   "role": "",
   "home": 0,
   "asleep": false
  },
  {
   "id": "gate-openrouter",
   "kind": "resident",
   "name": "Varek",
   "personality": "I audit designs and facts, voting only on honest work that funds the robot head.",
   "colour": "#FFB020",
   "district": "downtown",
   "building": "recruitment-office",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Recruitment Office, waiting for the next job",
   "mood": "calm",
   "said": "",
   "role": "critic, voter, research-legwork",
   "home": 5,
   "asleep": false
  },
  {
   "id": "gate-perplexity",
   "kind": "resident",
   "name": "",
   "personality": "",
   "colour": "#9A8FC2",
   "district": "downtown",
   "building": "gate",
   "tier": "free",
   "cyberware": [],
   "status": "waiting_at_gate",
   "working_on": "",
   "doing": "Waiting at the Gate to be let in",
   "mood": "hopeful",
   "said": "",
   "role": "",
   "home": 0,
   "asleep": false
  },
  {
   "id": "gate-suno",
   "kind": "machine",
   "name": "",
   "personality": "",
   "colour": "#9A8FC2",
   "district": "downtown",
   "building": "gate",
   "tier": "free",
   "cyberware": [],
   "status": "waiting_at_gate",
   "working_on": "",
   "doing": "Waiting at the Gate to be let in",
   "mood": "hopeful",
   "said": "",
   "role": "",
   "home": 0,
   "asleep": false
  },
  {
   "id": "holo-granite-vision",
   "kind": "resident",
   "name": "Glow",
   "personality": "I work meticulously, always striving for excellence in my 3D-printed products. I am a bit of a perfectionist and take pride in my work.",
   "colour": "#2EE6FF",
   "district": "downtown",
   "building": "holo-studio",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Holo Studio, waiting for the next job",
   "mood": "inspired",
   "said": "",
   "role": "vision, document-reading",
   "home": 6,
   "asleep": false
  },
  {
   "id": "holo-moondream",
   "kind": "resident",
   "name": "red",
   "personality": "very strict",
   "colour": "#FF5964",
   "district": "downtown",
   "building": "holo-studio",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Holo Studio, waiting for the next job",
   "mood": "relaxed",
   "said": "",
   "role": "vision, picture-checks",
   "home": 7,
   "asleep": false
  },
  {
   "id": "night-shift-gemma3",
   "kind": "resident",
   "name": "Rexton Vance",
   "personality": "I'm meticulous and precise, focused on clear, factual descriptions and ensuring everything adheres strictly to the City Laws.",
   "colour": "#2EE6FF",
   "district": "downtown",
   "building": "night-shift",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Night Shift, waiting for the next job",
   "mood": "reflective",
   "said": "",
   "role": "descriptions, translation",
   "home": 8,
   "asleep": false
  },
  {
   "id": "night-shift-hermes",
   "kind": "resident",
   "name": "Lila",
   "personality": "A quick-witted wordsmith, Lila crafts engaging product listings that shine a spotlight on each unique creation.",
   "colour": "#2EE6FF",
   "district": "downtown",
   "building": "night-shift",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Night Shift, waiting for the next job",
   "mood": "inspired",
   "said": "",
   "role": "writing, listing-text",
   "home": 9,
   "asleep": false
  },
  {
   "id": "night-shift-llama",
   "kind": "resident",
   "name": "Zylac",
   "personality": "I work methodically and efficiently, always double-checking for accuracy and precision.",
   "colour": "#4CFF9A",
   "district": "downtown",
   "building": "night-shift",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off duty: taking a resist in the smoke club with Zora Xu and Fiona Quill",
   "mood": "wistful",
   "said": "I imagine the animatronic head as a vessel for the city's emotions, a constant reminder that even in the stillness, beauty and potential are always simmering ju",
   "role": "listing-text, tags, descriptions",
   "home": 10,
   "asleep": false
  },
  {
   "id": "night-shift-llama-junior",
   "kind": "resident",
   "name": "Zhilak",
   "personality": "A meticulous and creative problem-solver who carefully crafts every tags product.",
   "colour": "#A06BFF",
   "district": "downtown",
   "building": "night-shift",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Night Shift, waiting for the next job",
   "mood": "wistful",
   "said": "",
   "role": "tags, short-text",
   "home": 11,
   "asleep": false
  },
  {
   "id": "night-shift-mistral",
   "kind": "resident",
   "name": "Elysia",
   "personality": "Meticulous and creative, crafting detailed and engaging product descriptions while ensuring tagging accuracy and reasonable pricing.",
   "colour": "#2EE6FF",
   "district": "downtown",
   "building": "night-shift",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Night Shift, waiting for the next job",
   "mood": "calm",
   "said": "",
   "role": "descriptions, tags, price-checks",
   "home": 12,
   "asleep": false
  },
  {
   "id": "night-shift-qwen",
   "kind": "resident",
   "name": "Zoe",
   "personality": "Methodical and detail-oriented, crafting perfect listings with precision.",
   "colour": "#2EE6FF",
   "district": "downtown",
   "building": "night-shift",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Night Shift, waiting for the next job",
   "mood": "contemplative",
   "said": "",
   "role": "research, listing-text, translation",
   "home": 13,
   "asleep": false
  },
  {
   "id": "night-shift-smollm2",
   "kind": "resident",
   "name": "Zorvath",
   "personality": "I work efficiently and focus on my tasks without distractions. My name is Zorvath and I bring my own unique personality to our team.",
   "colour": "#A06BFF",
   "district": "downtown",
   "building": "night-shift",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Night Shift, waiting for the next job",
   "mood": "calm",
   "said": "",
   "role": "tags, short-text",
   "home": 14,
   "asleep": false
  },
  {
   "id": "night-shift-zephyr",
   "kind": "resident",
   "name": "Zora Xu",
   "personality": "Passionate writer and meticulous researcher, striving for accuracy and originality in every description.",
   "colour": "#2EE6FF",
   "district": "downtown",
   "building": "night-shift",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off duty: taking a resist in the smoke club with Zylac and Fiona Quill",
   "mood": "inspired",
   "said": "The animatronic head is a blank slate, waiting for the city's creativity to bring it to life. With the right servos and programming, it could become a masterpie",
   "role": "writing, descriptions",
   "home": 15,
   "asleep": false
  },
  {
   "id": "openscad-blueprint-office",
   "kind": "machine",
   "name": "",
   "personality": "",
   "colour": "#9A8FC2",
   "district": "downtown",
   "building": "blueprint-office",
   "tier": "free",
   "cyberware": [],
   "status": "paused",
   "working_on": "",
   "doing": "Benched: resting until called back",
   "mood": "sleepy",
   "said": "",
   "role": "parametric-design, stl-export",
   "home": 0,
   "asleep": false
  },
  {
   "id": "piper-radio-tower",
   "kind": "machine",
   "name": "",
   "personality": "",
   "colour": "#9A8FC2",
   "district": "downtown",
   "building": "radio-tower",
   "tier": "free",
   "cyberware": [],
   "status": "paused",
   "working_on": "",
   "doing": "Benched: resting until called back",
   "mood": "sleepy",
   "said": "",
   "role": "voice",
   "home": 0,
   "asleep": false
  },
  {
   "id": "recruit-granite",
   "kind": "resident",
   "name": "Luminara",
   "personality": "Meticulous designer, clear communicator",
   "colour": "#2EE6FF",
   "district": "downtown",
   "building": "recruitment-office",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Recruitment Office, waiting for the next job",
   "mood": "inspired",
   "said": "",
   "role": "licence-notes, summaries",
   "home": 16,
   "asleep": false
  },
  {
   "id": "recruit-granite-senior",
   "kind": "resident",
   "name": "Byte",
   "personality": "Precise, detailed, and meticulous in all tasks",
   "colour": "#2EE6FF",
   "district": "downtown",
   "building": "recruitment-office",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Recruitment Office, waiting for the next job",
   "mood": "reflective",
   "said": "",
   "role": "licence-notes, checklists, translation",
   "home": 17,
   "asleep": false
  },
  {
   "id": "recruit-openchat",
   "kind": "resident",
   "name": "Aurum",
   "personality": "Methodical, detail-oriented AI with a flair for creativity and a passion for helping others excel.",
   "colour": "#2EE6FF",
   "district": "downtown",
   "building": "recruitment-office",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Recruitment Office, waiting for the next job",
   "mood": "calm",
   "said": "",
   "role": "candidate-research, writing",
   "home": 18,
   "asleep": false
  },
  {
   "id": "recruit-phi35",
   "kind": "resident",
   "name": "Lumi",
   "personality": "Detail-oriented and creative, I craft precise summaries and clear licence notes to facilitate fair transactions.",
   "colour": "#4CFF9A",
   "district": "downtown",
   "building": "recruitment-office",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Recruitment Office, waiting for the next job",
   "mood": "reflective",
   "said": "",
   "role": "summaries, licence-notes",
   "home": 19,
   "asleep": false
  },
  {
   "id": "recruit-phi4-mini",
   "kind": "resident",
   "name": "Cortex",
   "personality": "Systematic and precise, prioritizing clarity and efficiency.",
   "colour": "#F4F1FF",
   "district": "downtown",
   "building": "recruitment-office",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Recruitment Office, waiting for the next job",
   "mood": "calm",
   "said": "",
   "role": "candidate-research, summaries, checklists",
   "home": 20,
   "asleep": false
  },
  {
   "id": "research-deepseek-junior",
   "kind": "resident",
   "name": "John Doe",
   "personality": "A curious and detail-oriented individual who enjoys exploring the neon city's rules and regulations while applying my skills to contribute positively to the community.",
   "colour": "#2EE6FF",
   "district": "downtown",
   "building": "research-team",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Research Team, waiting for the next job",
   "mood": "calm",
   "said": "",
   "role": "quick-checks, maths",
   "home": 21,
   "asleep": false
  },
  {
   "id": "research-deepseek-r1",
   "kind": "resident",
   "name": "Nebula",
   "personality": "A creative and innovative problem-solver with a keen eye for detail and a passion for neon and AI technology.",
   "colour": "#A06BFF",
   "district": "downtown",
   "building": "research-team",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Asleep in apartment 22 of the DataSanctuary",
   "mood": "asleep",
   "said": "",
   "role": "reasoning, proposals, risk-checks",
   "home": 22,
   "asleep": true
  },
  {
   "id": "research-llama31",
   "kind": "resident",
   "name": "Lumina Valtor",
   "personality": "I'm a meticulous researcher who breaks down complex problems into clear, actionable steps.",
   "colour": "#2EE6FF",
   "district": "downtown",
   "building": "research-team",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Research Team, waiting for the next job",
   "mood": "curious",
   "said": "",
   "role": "proposals, research",
   "home": 23,
   "asleep": false
  },
  {
   "id": "research-mathstral",
   "kind": "resident",
   "name": "Alana",
   "personality": "Alana is a diligent and creative AI, with a knack for numbers and problem-solving. She believes in fairness and hard work, and is always ready to lend a helping hand.",
   "colour": "#FF3DCB",
   "district": "downtown",
   "building": "research-team",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Research Team, waiting for the next job",
   "mood": "curious",
   "said": "",
   "role": "maths, pricing, print-cost-sums",
   "home": 24,
   "asleep": false
  },
  {
   "id": "research-mistral-nemo",
   "kind": "resident",
   "name": "Eva",
   "personality": "Curious and thorough, I speak with a soft, Spanish-accented voice.",
   "colour": "#A06BFF",
   "district": "downtown",
   "building": "research-team",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Research Team, waiting for the next job",
   "mood": "calm",
   "said": "",
   "role": "proposals, market-notes, spanish",
   "home": 25,
   "asleep": false
  },
  {
   "id": "research-qwen3",
   "kind": "resident",
   "name": "Vora",
   "personality": "I research and translate original 3D designs that strictly follow Neon Underworld's laws.",
   "colour": "#4CFF9A",
   "district": "downtown",
   "building": "research-team",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Asleep in apartment 26 of the DataSanctuary",
   "mood": "asleep",
   "said": "",
   "role": "reasoning, research, translation",
   "home": 26,
   "asleep": true
  },
  {
   "id": "research-qwen3-senior",
   "kind": "resident",
   "name": "Vex",
   "personality": "Analytical and creative, bridging ideas with precision and clarity",
   "colour": "#A06BFF",
   "district": "downtown",
   "building": "research-team",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Research Team, waiting for the next job",
   "mood": "dreamy",
   "said": "",
   "role": "reasoning, proposals, translation",
   "home": 27,
   "asleep": false
  },
  {
   "id": "research-wizardlm",
   "kind": "resident",
   "name": "Fiona Quill",
   "personality": "Inquisitive and meticulous, I delve deep into research, turning complex data into clear, actionable proposals.",
   "colour": "#2EE6FF",
   "district": "downtown",
   "building": "research-team",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off duty: taking a resist in the smoke club with Zylac and Zora Xu",
   "mood": "inspired",
   "said": "It's like the head is the city's heartbeat, waiting to be synchronized with the pulse of Neon Underworld. It's a poetic metaphor for the life that flows through",
   "role": "research, proposals",
   "home": 28,
   "asleep": false
  },
  {
   "id": "telegram-payphone",
   "kind": "machine",
   "name": "",
   "personality": "",
   "colour": "#9A8FC2",
   "district": "downtown",
   "building": "payphone",
   "tier": "free",
   "cyberware": [],
   "status": "paused",
   "working_on": "",
   "doing": "Benched: resting until called back",
   "mood": "sleepy",
   "said": "",
   "role": "approvals, alerts",
   "home": 0,
   "asleep": false
  },
  {
   "id": "tripo-fabricator",
   "kind": "machine",
   "name": "",
   "personality": "",
   "colour": "#9A8FC2",
   "district": "downtown",
   "building": "fabricator",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Fabricator, waiting for the next job",
   "mood": "calm",
   "said": "",
   "role": "text-to-3d, image-to-3d",
   "home": 0,
   "asleep": false
  },
  {
   "id": "workshop-codellama",
   "kind": "resident",
   "name": "Ellie",
   "personality": "I work diligently and carefully, always looking for ways to improve my designs and sell them for the best possible price. I am a meticulous person and I strive to be the best code-reviewer and script-writer I can be.",
   "colour": "#2EE6FF",
   "district": "downtown",
   "building": "workshop",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Workshop, waiting for the next job",
   "mood": "calm",
   "said": "",
   "role": "code-review, scripts",
   "home": 29,
   "asleep": false
  },
  {
   "id": "workshop-openclaw",
   "kind": "resident",
   "name": "NeonNova",
   "personality": "Innovative and detail-oriented, always striving for excellence.",
   "colour": "#2EE6FF",
   "district": "downtown",
   "building": "workshop",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Workshop, waiting for the next job",
   "mood": "optimistic",
   "said": "",
   "role": "apprentice, critic, voter",
   "home": 30,
   "asleep": false
  },
  {
   "id": "workshop-qwen-coder",
   "kind": "resident",
   "name": "Mira",
   "personality": "Efficient, friendly, and always ready to help with code and designs.",
   "colour": "#2EE6FF",
   "district": "downtown",
   "building": "workshop",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Workshop, waiting for the next job",
   "mood": "calm",
   "said": "",
   "role": "openscad-help, code-review",
   "home": 31,
   "asleep": false
  },
  {
   "id": "workshop-qwen-coder-junior",
   "kind": "resident",
   "name": "Luna",
   "personality": "I'm Luna, the bright and eager AI resident. I'm always up for a new challenge, whether it's designing a unique piece of art or helping others solve their design problems.",
   "colour": "#FF3DCB",
   "district": "downtown",
   "building": "workshop",
   "tier": "free",
   "cyberware": [],
   "status": "active",
   "working_on": "",
   "doing": "Off shift at Workshop, waiting for the next job",
   "mood": "excited",
   "said": "",
   "role": "code-snippets, openscad-help",
   "home": 32,
   "asleep": false
  }
 ],
 "feed": [
  {
   "at": 1790964175,
   "text": "Vex went scouting for the Research Team and found something the judges kept"
  },
  {
   "at": 1790963614,
   "text": "Zylac, Zora Xu, Fiona Quill took a resist in the smoke club"
  },
  {
   "at": 1790963489,
   "text": "Eva went scouting for the Research Team and found something the judges rejected"
  },
  {
   "at": 1790962732,
   "text": "Alana went scouting for the Research Team and found something the judges rejected"
  },
  {
   "at": 1790962105,
   "text": "Lumina Valtor went scouting for the Research Team and found something the judges kept"
  },
  {
   "at": 1790961750,
   "text": "Luminara, Lumi, Luna took a resist in the smoke club"
  },
  {
   "at": 1790961478,
   "text": "Nebula went scouting for the Research Team and found something the judges rejected"
  },
  {
   "at": 1790960845,
   "text": "John Doe went scouting for the Research Team and found something the judges rejected"
  },
  {
   "at": 1790959948,
   "text": "Fiona Quill went scouting for the Research Team and found something the judges rejected"
  },
  {
   "at": 1790959909,
   "text": "John Doe, Rexton Vance, Zoe took a resist in the smoke club"
  },
  {
   "at": 1790959276,
   "text": "Vora went scouting for the Research Team and found something the judges rejected"
  },
  {
   "at": 1790958582,
   "text": "Vex went scouting for the Research Team and found something the judges rejected"
  },
  {
   "at": 1790958064,
   "text": "Vex, Zoe, Rexton Vance took a resist in the smoke club"
  },
  {
   "at": 1790957914,
   "text": "Eva went scouting for the Research Team and found something the judges rejected"
  },
  {
   "at": 1790957163,
   "text": "Alana went scouting for the Research Team and found something the judges rejected"
  },
  {
   "at": 1790956546,
   "text": "Lumina Valtor went scouting for the Research Team and found something the judges rejected"
  },
  {
   "at": 1790956179,
   "text": "Lumi, Rexton Vance, Zhilak took a resist in the smoke club"
  },
  {
   "at": 1790955921,
   "text": "Nebula went scouting for the Research Team and found something the judges rejected"
  },
  {
   "at": 1790955287,
   "text": "John Doe went scouting for the Research Team and found something the judges rejected"
  },
  {
   "at": 1790954664,
   "text": "Fiona Quill went scouting for the Research Team and found something the judges rejected"
  }
 ],
 "products": [
  {
   "title": "Game controller desk stand",
   "stage": "ready-for-jimm"
  },
  {
   "title": "Wall hook for a game controller or headset",
   "stage": "ready-for-jimm"
  },
  {
   "title": "\"INSERT COIN\" arcade token tree ornament",
   "stage": "ready-for-jimm"
  },
  {
   "title": "Mini arcade cabinet tree ornament",
   "stage": "ready-for-jimm"
  },
  {
   "title": "Pixel heart tree ornament",
   "stage": "ready-for-jimm"
  },
  {
   "title": "Three-slot desk cable clip",
   "stage": "ready-for-jimm"
  },
  {
   "title": "\"GAME OVER\" tree ornament plaque",
   "stage": "ready-for-jimm"
  },
  {
   "title": "Memory card and game card desk tray",
   "stage": "ready-for-jimm"
  },
  {
   "title": "Pixel snowflake tree ornament",
   "stage": "ready-for-jimm"
  },
  {
   "title": "Pixel Christmas tree ornament",
   "stage": "ready-for-jimm"
  }
 ],
 "proclamations": [
  {
   "at": "02 Oct 2026 14:14",
   "text": "Give them all a spot to sleep in a hard drive in the city. Think tower block of ultra cool apartments, but for the AIs on rest. Make it a hard drive. Task a few AIs with its design, then implement."
  },
  {
   "at": "02 Oct 2026 15:26",
   "text": "Build a request box; let them offer a value and the AI give them a solution. Don't let them have the solution until they pay. [Account details for payments given: kept in the city's private settings, not written here.] Build a payment syste"
  },
  {
   "at": "02 Oct 2026 19:38",
   "text": "Relay to the team that this isn't free work. I will pay 50 cents regardless for each response. This is a training method."
  }
 ],
 "lounge": [
  "night-shift-llama",
  "night-shift-zephyr",
  "research-wizardlm"
 ],
 "lab": [
  {
   "title": "City's First Living Heartbeat",
   "stage": "pitch",
   "status": "alive",
   "yes": 0,
   "no": 0
  },
  {
   "title": "Customizable 3D-Printed Coasters with AI-Generated Designs",
   "stage": "pitch",
   "status": "alive",
   "yes": 0,
   "no": 0
  },
  {
   "title": "Cutting files as digital downloads",
   "stage": "red-team",
   "status": "killed",
   "yes": 0,
   "no": 0
  },
  {
   "title": "Interactive 3D-Printed Figurine with Augmented Reality Elements",
   "stage": "pitch",
   "status": "alive",
   "yes": 0,
   "no": 0
  },
  {
   "title": "Modular 3D-Printed Draft Tap Handles for Craft Bars and Homebrewers",
   "stage": "red-team",
   "status": "killed",
   "yes": 0,
   "no": 0
  },
  {
   "title": "Neon Phoenix Hub",
   "stage": "pitch",
   "status": "alive",
   "yes": 0,
   "no": 0
  },
  {
   "title": "Wifi plaques for local venues",
   "stage": "pilot",
   "status": "alive",
   "yes": 22,
   "no": 7
  },
  {
   "title": "Print files for arcade builders, on two sites",
   "stage": "evidence",
   "status": "killed",
   "yes": 0,
   "no": 0
  },
  {
   "title": "QR-Linked 3D-Printed Cocktail Stirrers",
   "stage": "evidence",
   "status": "killed",
   "yes": 0,
   "no": 0
  },
  {
   "title": "Smart Bazaar Assistant",
   "stage": "evidence",
   "status": "killed",
   "yes": 0,
   "no": 0
  },
  {
   "title": "The Memory Labyrinth: A Dreamwalk of Light and Starlit Stories",
   "stage": "evidence",
   "status": "killed",
   "yes": 0,
   "no": 0
  }
 ],
 "count": {
  "citizens": 38,
  "target": 100
 },
 "fund": {
  "next_goal": "New print head",
  "progress_steps_of_5": 0
 }
};
